# Tahap 1: Build aplikasi Vue
FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package*.json ./


RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS production-stagez
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80

# Jalankan Nginx
CMD ["nginx", "-g", "daemon off;"]