server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Fallback routing utama untuk Vue Router
        try_files $uri $uri/ /index.html;
    }

    # Optimasi Tech/IT: Cache control untuk aset statis agar web me-load sangat cepat
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|woff)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # Hindari Nginx menampilkan versi server saat terjadi error (Keamanan dasar)
    server_tokens off;
}